services:
  - type: static
    name: lough-skin-frontend
    env: static
    buildCommand: npm run build
    publishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
